{
 "title": "HTTP Server Korp - Production Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requests / 5m",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 5 },
   "targets": [
    {
     "expr": "increase(http_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 16, "h": 7 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "Requests por Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 16, "h": 7 },
   "targets": [
    {
     "expr": "sum by (endpoint) (http_requests_total)"
    }
   ]
  },
  {
   "title": "Go Memory Usage (Heap)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 19, "w": 8, "h": 6 },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 19, "w": 8, "h": 6 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 25, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "HTTP Scrape Health",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 25, "w": 8, "h": 6 },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}